# Generated by Django 4.2.12 on 2024-06-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='blog',
            new_name='cloth',
        ),
    ]
