# Generated by Django 4.2.12 on 2024-05-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Models',
            new_name='BlogModels',
        ),
    ]
